import { useState } from "react";
import { Download, FileSpreadsheet, Receipt } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import type { PortfolioCard } from "@/hooks/usePortfolio";

interface PortfolioExportProps {
  portfolio: PortfolioCard[];
  livePrices?: Record<string, { market: number; low: number; mid: number; high: number }>;
}

const PortfolioExport = ({ portfolio, livePrices }: PortfolioExportProps) => {
  const { tier } = useAuth();
  const isWhale = tier === "institutional";
  const [exporting, setExporting] = useState<string | null>(null);

  const downloadCSV = (filename: string, rows: string[][]) => {
    const csv = rows.map((r) => r.map((c) => `"${String(c).replace(/"/g, '""')}"`).join(",")).join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportPortfolio = () => {
    setExporting("portfolio");
    const header = ["Card Name", "Set", "Number", "Quantity", "Purchase Price", "Current Market Price", "Total Value", "P&L", "P&L %"];
    const rows = portfolio.map((card) => {
      const live = livePrices?.[card.card_api_id];
      const currentPrice = live?.market ?? 0;
      const totalValue = currentPrice * card.quantity;
      const costBasis = (card.purchase_price ?? 0) * card.quantity;
      const pnl = costBasis > 0 ? totalValue - costBasis : 0;
      const pnlPct = costBasis > 0 ? ((pnl / costBasis) * 100).toFixed(2) : "N/A";
      return [
        card.card_name,
        card.card_set,
        card.card_number,
        String(card.quantity),
        card.purchase_price ? `$${card.purchase_price.toFixed(2)}` : "N/A",
        `$${currentPrice.toFixed(2)}`,
        `$${totalValue.toFixed(2)}`,
        costBasis > 0 ? `$${pnl.toFixed(2)}` : "N/A",
        typeof pnlPct === "string" ? pnlPct : `${pnlPct}%`,
      ];
    });
    downloadCSV(`pokepulse-portfolio-${new Date().toISOString().slice(0, 10)}.csv`, [header, ...rows]);
    setTimeout(() => setExporting(null), 1000);
  };

  const exportTaxReport = () => {
    setExporting("tax");
    const header = [
      "Card Name", "Set", "Quantity", "Date Acquired", "Purchase Price (per unit)",
      "Current FMV (per unit)", "Total Cost Basis", "Total FMV",
      "Unrealized Gain/Loss", "Holding Period", "Tax Treatment"
    ];
    const rows = portfolio.map((card) => {
      const live = livePrices?.[card.card_api_id];
      const currentPrice = live?.market ?? 0;
      const costBasis = (card.purchase_price ?? 0) * card.quantity;
      const fmv = currentPrice * card.quantity;
      const gainLoss = costBasis > 0 ? fmv - costBasis : 0;
      const acquiredDate = new Date(card.added_at);
      const now = new Date();
      const holdingDays = Math.floor((now.getTime() - acquiredDate.getTime()) / (1000 * 60 * 60 * 24));
      const holdingPeriod = holdingDays > 365 ? "Long-term" : "Short-term";
      const taxRate = holdingDays > 365 ? "15-20% (LTCG)" : "Ordinary Income (STCG)";
      return [
        card.card_name,
        card.card_set,
        String(card.quantity),
        acquiredDate.toLocaleDateString("en-US"),
        card.purchase_price ? `$${card.purchase_price.toFixed(2)}` : "N/A",
        `$${currentPrice.toFixed(2)}`,
        costBasis > 0 ? `$${costBasis.toFixed(2)}` : "N/A",
        `$${fmv.toFixed(2)}`,
        costBasis > 0 ? `$${gainLoss.toFixed(2)}` : "N/A",
        holdingPeriod,
        taxRate,
      ];
    });

    // Add summary row
    const totalCost = portfolio.reduce((s, c) => s + (c.purchase_price ?? 0) * c.quantity, 0);
    const totalFMV = portfolio.reduce((s, c) => s + (livePrices?.[c.card_api_id]?.market ?? 0) * c.quantity, 0);
    const totalGain = totalCost > 0 ? totalFMV - totalCost : 0;
    rows.push([
      "TOTAL", "", String(portfolio.reduce((s, c) => s + c.quantity, 0)),
      "", "", "",
      totalCost > 0 ? `$${totalCost.toFixed(2)}` : "N/A",
      `$${totalFMV.toFixed(2)}`,
      totalCost > 0 ? `$${totalGain.toFixed(2)}` : "N/A",
      "", ""
    ]);
    rows.push([]);
    rows.push(["IMPORTANT DISCLAIMER: This report is for informational purposes only and does not constitute tax advice."]);
    rows.push(["PGVA Ventures, LLC is NOT a Certified Public Accountant (CPA), tax advisor, or licensed financial professional."]);
    rows.push(["Cost basis calculations use FIFO (First-In, First-Out) methodology. Holding period classification follows IRS guidelines (>1 year = Long-term)."]);
    rows.push(["Figures are estimates based on available market data. Consult a qualified CPA or tax professional for official tax filing."]);
    rows.push([`Generated by Poke-Pulse Ticker on ${new Date().toLocaleDateString("en-US")}. © PGVA Ventures, LLC. All rights reserved.`]);

    downloadCSV(`pokepulse-tax-report-${new Date().toISOString().slice(0, 10)}.csv`, [header, ...rows]);
    setTimeout(() => setExporting(null), 1000);
  };

  if (!isWhale) return null;

  return (
    <div className="terminal-card p-4">
      <div className="flex items-center justify-between mb-3">
        <h3 className="font-mono text-xs tracking-widest text-secondary uppercase font-semibold flex items-center gap-2">
          <FileSpreadsheet className="w-3.5 h-3.5" /> Whale Exports
        </h3>
        <span className="font-mono text-[9px] text-terminal-amber px-2 py-0.5 rounded bg-terminal-amber/10 border border-terminal-amber/20">
          🐋 WHALE EXCLUSIVE
        </span>
      </div>
      <div className="flex flex-col sm:flex-row gap-2">
        <button
          onClick={exportPortfolio}
          disabled={!!exporting}
          className="flex-1 flex items-center justify-center gap-2 font-mono text-xs font-semibold bg-primary/10 text-primary border border-primary/30 rounded px-3 py-2.5 hover:bg-primary/20 transition-colors disabled:opacity-50"
        >
          <Download className="w-3.5 h-3.5" />
          {exporting === "portfolio" ? "Downloading…" : "Export Portfolio CSV"}
        </button>
        <button
          onClick={exportTaxReport}
          disabled={!!exporting}
          className="flex-1 flex items-center justify-center gap-2 font-mono text-xs font-semibold bg-terminal-amber/10 text-terminal-amber border border-terminal-amber/30 rounded px-3 py-2.5 hover:bg-terminal-amber/20 transition-colors disabled:opacity-50"
        >
          <Receipt className="w-3.5 h-3.5" />
          {exporting === "tax" ? "Downloading…" : "Capital Gains Tax Report"}
        </button>
      </div>
      <p className="font-mono text-[9px] text-muted-foreground mt-2">
        Tax report includes holding period analysis, short/long-term classification, and unrealized gains.
      </p>
      <div className="mt-2 px-2 py-1.5 rounded border border-terminal-amber/20 bg-terminal-amber/5">
        <p className="font-mono text-[8px] text-terminal-amber/80 leading-relaxed">
          ⚠️ DISCLAIMER: Tax reports are for informational purposes only and do not constitute tax, legal, or financial advice. 
          PGVA Ventures, LLC is NOT a Certified Public Accountant (CPA) or licensed tax advisor. Cost basis uses FIFO methodology. 
          Holding periods follow IRS definitions (assets held &gt;1 year = Long-term Capital Gains). Consult a qualified CPA or 
          tax professional before making any tax-related decisions. PGVA Ventures, LLC assumes no liability for the accuracy of 
          tax calculations or any financial decisions made based on this data. See <a href="/terms" className="underline">Terms of Service</a>.
        </p>
      </div>
    </div>
  );
};

export default PortfolioExport;
